export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS';
export const GET_CHAT_FAIL = 'GET_CHAT_FAIL';
export const GET_CHAT_REQUEST = 'GET_CHAT_REQUEST';

export const GET_SINGLE_CHAT_SUCCESS = 'GET_SINGLE_CHAT_SUCCESS';
export const GET_SINGLE_CHAT_FAIL = 'GET_SINGLE_CHAT_FAIL';
export const GET_SINGLE_CHAT_REQUEST = 'GET_SINGLE_CHAT_REQUEST';